-- Migration 010 — org merge candidates (Phase F / M4).
--
-- One table: organization_merge_candidate.
--   DERIVED, rebuildable proposals from high-recall blocking. Safe to truncate.
--   This is NOT a decision — it is "these two orgs MIGHT be the same, here's why".
--   Human review (or a future auto-merge) turns a candidate into a durable row in
--   organization_merge_decision (migration 009), which alone feeds canonicalize.
--
-- CADENCE (important): candidate generation does NOT run inside the canonical
-- replay. Canonicalize stays a cheap, deterministic replay of durable decisions;
-- candidate generation + scoring is a separate, slower batch (`cli candidates`).
-- Because canonicalize TRUNCATEs organizations with `restart identity`, org ids
-- change every rebuild — so this table is listed in truncate_canonical and is
-- regenerated by the batch afterward. The rebuild-stable identity is the
-- norm_key pair (left_key/right_key), which is also how gold pairs and
-- organization_merge_decision are keyed; the org id columns are convenience FKs,
-- valid only within the generation that produced them.
--
-- Design: experiments/entity_resolution/PHASE_E_DESIGN.md (M4 extension).

create table if not exists organization_merge_candidate (
    id              bigserial primary key,
    -- Identity: an UNORDERED pair, canonicalized so left_key < right_key. The
    -- check + unique make (A,B)/(B,A) duplicates and self-pairs unrepresentable.
    -- collate "C": order by byte/code-point, matching Python's str ordering in
    -- candidates.order_pair. Without it the `<` check uses the DB's locale
    -- collation (which e.g. ignores spaces) and disagrees with the app, so
    -- correctly-ordered pairs would fail the constraint.
    left_key        text collate "C" not null,
    right_key       text collate "C" not null,
    -- Convenience FKs into the orgs of THIS generation (see CADENCE note).
    left_org_id     bigint not null references organizations (id),
    right_org_id    bigint not null references organizations (id),
    -- Provenance: which blocker(s) surfaced this pair. Preserved through dedup
    -- (a pair found by trigram AND rare-token carries both), so we can compute
    -- each blocker's MARGINAL recall and retire dead-weight blockers.
    reasons         text[] not null default '{}',
    -- Scoring (M5 scorer). features is a NAMED dict so a row predating a
    -- feature is representable (missing key) vs feature=0. Tie it to
    -- feature_version — the day a feature is added, old rows are honestly
    -- stale. Model OUTPUTS (probability, predicted_label) live in
    -- model_predictions (migration 011), not here — a single mutable column
    -- can't hold multiple model versions' predictions for the same candidate.
    features        jsonb,
    feature_version text,
    status          text   not null default 'pending'
                    check (status in ('pending','scored','queued','decided','suppressed')),
    generated_at    timestamptz not null default now(),
    check (left_key < right_key),
    unique (left_key, right_key)
);
create index if not exists omc_left_org_idx  on organization_merge_candidate (left_org_id);
create index if not exists omc_right_org_idx on organization_merge_candidate (right_org_id);
create index if not exists omc_status_idx    on organization_merge_candidate (status);

comment on table organization_merge_candidate is
    'Derived high-recall merge proposals (blocking output). Safe to truncate; '
    'rebuilt by `cli candidates`, NOT by canonicalize. Identity is the norm_key '
    'pair (left_key<right_key); org ids are per-generation convenience FKs. '
    'Source of truth for merges is organization_merge_decision (migration 009).';
comment on column organization_merge_candidate.reasons is
    'Blocker tags that surfaced this pair (e.g. {trigram,rare_token}); union-merged across blockers.';
comment on column organization_merge_candidate.features is
    'Named feature dict for the scorer; null until scored. Interpret alongside feature_version.';
